inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - '**/*.rb'

Metrics/BlockLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods: []

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
  # Change the default 80 chars limit value
  Max: 120

Metrics/MethodLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 10

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  MinSize: 3
